name: Build and Push (GHCR)

on:
  push:
    branches:
      - release
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "TAG_ENV=prod" >> $GITHUB_ENV
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          else
            echo "TAG_ENV=hml" >> $GITHUB_ENV
            echo "ENV_NAME=hml" >> $GITHUB_ENV
          fi

      - name: Read Version
        id: version
        run: |
          VERSION=$(grep "__version__ =" app/version.py | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
          # context . 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.TAG_ENV }}-latest
            ghcr.io/${{ github.repository }}:${{ env.TAG_ENV }}-v${{ steps.version.outputs.VERSION }}

      - name: Update Manifest
        run: |
          mkdir -p manifest
          cat <<EOF > manifest/${{ env.ENV_NAME }}.json
          {
            "version": "${{ steps.version.outputs.VERSION }}",
            "tag": "${{ env.TAG_ENV }}-v${{ steps.version.outputs.VERSION }}",
            "date": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')",
            "commit": "${{ github.sha }}"
          }
          EOF

      - name: Deploy Manifest to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manifest
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
